/**
 * Verb lexicon for The Tense Atlas.
 * Regular verbs omit forms; irregulars override past/participle (and sometimes gerund/s).
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.TenseAtlasVerbs = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  function regular(lemma, scene, extra) {
    return Object.assign({ lemma: lemma, scene: scene }, extra || {});
  }

  function irr(lemma, scene, past, participle, extra) {
    return Object.assign(
      { lemma: lemma, scene: scene, past: past, participle: participle },
      extra || {}
    );
  }

  const VERBS = [
    irr("be", "patient with the crew", "was", "been", { s: "is", gerund: "being" }),
    irr("have", "enough time", "had", "had", { s: "has", stative: true }),
    irr("do", "the hard work", "did", "done", { s: "does" }),
    irr("say", "the coordinates aloud", "said", "said"),
    irr("go", "to the harbor", "went", "gone"),
    irr("get", "the message", "got", "gotten", { participles: ["got"] }),
    irr("make", "a careful plan", "made", "made"),
    irr("know", "the harbor by heart", "knew", "known", { stative: true }),
    irr("think", "about the route", "thought", "thought"),
    irr("take", "the coastal path", "took", "taken"),
    irr("see", "the lighthouse", "saw", "seen"),
    irr("come", "into the chart room", "came", "come"),
    irr("find", "a shorter passage", "found", "found"),
    irr("give", "clear directions", "gave", "given"),
    irr("tell", "the truth about the tide", "told", "told"),
    irr("feel", "the wind shift", "felt", "felt"),
    irr("become", "sure of the heading", "became", "become"),
    irr("leave", "the old maps behind", "left", "left"),
    irr("put", "the compass on the desk", "put", "put"),
    irr("mean", "every word of it", "meant", "meant", { stative: true }),
    irr("keep", "a steady course", "kept", "kept"),
    irr("let", "the crew rest", "let", "let"),
    irr("begin", "the morning watch", "began", "begun"),
    irr("show", "the marked channel", "showed", "shown", { participles: ["showed"] }),
    irr("hear", "the bell across the water", "heard", "heard"),
    irr("run", "along the quay", "ran", "run"),
    irr("hold", "the tiller steady", "held", "held"),
    irr("bring", "the charts upstairs", "brought", "brought"),
    irr("write", "a letter home", "wrote", "written"),
    irr("sit", "by the window", "sat", "sat"),
    irr("stand", "on the foredeck", "stood", "stood"),
    irr("lose", "sight of the cape", "lost", "lost"),
    irr("pay", "attention to the depth", "paid", "paid"),
    irr("meet", "the harbor master", "met", "met"),
    irr("set", "the lantern in place", "set", "set"),
    irr("lead", "the survey party", "led", "led"),
    irr("understand", "the warning", "understood", "understood", { stative: true }),
    irr("speak", "in a low voice", "spoke", "spoken"),
    irr("read", "the tide table", "read", "read"),
    irr("spend", "an hour on the fix", "spent", "spent"),
    irr("grow", "quiet before the storm", "grew", "grown"),
    irr("win", "the coastal race", "won", "won"),
    irr("teach", "the new crew the knots", "taught", "taught"),
    irr("buy", "fresh provisions", "bought", "bought"),
    irr("send", "a signal to shore", "sent", "sent"),
    irr("build", "a shelter on the point", "built", "built"),
    irr("fall", "behind the schedule", "fell", "fallen"),
    irr("cut", "the frayed line", "cut", "cut"),
    irr("sell", "the surplus canvas", "sold", "sold"),
    irr("break", "the morning silence", "broke", "broken"),
    irr("hit", "the reef in the fog", "hit", "hit"),
    irr("eat", "before the watch", "ate", "eaten"),
    irr("catch", "the first light", "caught", "caught"),
    irr("draw", "a new coastline", "drew", "drawn"),
    irr("choose", "the safer channel", "chose", "chosen"),
    irr("drink", "the last of the coffee", "drank", "drunk"),
    irr("sleep", "through the calm", "slept", "slept"),
    irr("drive", "the boat to windward", "drove", "driven"),
    irr("ride", "the incoming swell", "rode", "ridden"),
    irr("fly", "a signal flag", "flew", "flown"),
    irr("swim", "to the dinghy", "swam", "swum"),
    irr("sing", "an old work song", "sang", "sung"),
    irr("wear", "the heavy coat", "wore", "worn"),
    irr("forget", "the earlier heading", "forgot", "forgotten"),
    irr("throw", "a line to the pier", "threw", "thrown"),
    irr("blow", "from the northwest", "blew", "blown"),
    irr("lie", "on the sunlit deck", "lay", "lain", { gerund: "lying" }),
    irr("lay", "the chart flat", "laid", "laid"),
    irr("rise", "with the early tide", "rose", "risen"),
    irr("hang", "the lantern in the hall", "hung", "hung"),
    irr("steal", "a glance at the glass", "stole", "stolen"),
    irr("hide", "the spare key", "hid", "hidden"),
    irr("bite", "into the hard bread", "bit", "bitten"),
    irr("freeze", "on the night watch", "froze", "frozen"),
    irr("shake", "the water from the coat", "shook", "shaken"),
    irr("wake", "before the bell", "woke", "woken"),
    irr("fight", "the contrary current", "fought", "fought"),
    irr("feed", "the stove with driftwood", "fed", "fed"),
    irr("dig", "a mark in the sand", "dug", "dug"),
    irr("bend", "the sail to the spar", "bent", "bent"),
    irr("lend", "a spare compass", "lent", "lent"),
    irr("deal", "with the sudden squall", "dealt", "dealt"),
    irr("hurt", "after the long haul", "hurt", "hurt"),
    irr("cost", "more than expected", "cost", "cost", { stative: true }),
    irr("shut", "the chart-room door", "shut", "shut"),
    irr("split", "the watch into pairs", "split", "split"),
    irr("spread", "the map on the table", "spread", "spread"),
    irr("stick", "to the original plan", "stuck", "stuck"),
    irr("strike", "the colors at dusk", "struck", "struck"),
    irr("swear", "the bearing was true", "swore", "sworn"),
    irr("sweep", "the deck at dawn", "swept", "swept"),
    irr("swing", "the boom across", "swung", "swung"),
    irr("tear", "the old page out", "tore", "torn"),
    irr("ring", "the watch bell", "rang", "rung"),
    irr("sink", "beneath the fog", "sank", "sunk"),
    irr("slide", "the drawer shut", "slid", "slid"),
    irr("light", "the cabin lamp", "lit", "lit", { pasts: ["lighted"], participles: ["lighted"] }),
    irr("quit", "the crowded dock", "quit", "quit"),
    irr("beat", "against the tide", "beat", "beaten"),
    irr("bind", "the loose pages", "bound", "bound"),
    irr("bleed", "through the old bandage", "bled", "bled"),
    irr("breed", "trouble in close quarters", "bred", "bred"),
    irr("burst", "into the chart room", "burst", "burst"),
    irr("cling", "to the rail", "clung", "clung"),
    irr("creep", "along the cliff path", "crept", "crept"),
    irr("flee", "the incoming weather", "fled", "fled"),
    irr("fling", "the rope ashore", "flung", "flung"),
    irr("forgive", "the earlier mistake", "forgave", "forgiven"),
    irr("grind", "the coffee before dawn", "ground", "ground"),
    irr("kneel", "beside the locker", "knelt", "knelt", { pasts: ["kneeled"], participles: ["kneeled"] }),
    irr("leap", "onto the quay", "leaped", "leaped", { pasts: ["leapt"], participles: ["leapt"] }),
    irr("seek", "a quieter anchorage", "sought", "sought"),
    irr("shine", "across the water", "shone", "shone"),
    irr("shoot", "a bearing on the cape", "shot", "shot"),
    irr("shrink", "from the cold spray", "shrank", "shrunk"),
    irr("spin", "the wheel to port", "spun", "spun"),
    irr("spit", "the salt from a lip", "spit", "spit", { pasts: ["spat"], participles: ["spat"] }),
    irr("spring", "a leak near the keel", "sprang", "sprung"),
    irr("sting", "in the winter air", "stung", "stung"),
    irr("stink", "of tar and oakum", "stank", "stunk"),
    irr("stride", "across the deck", "strode", "stridden"),
    irr("string", "the flags in order", "strung", "strung"),
    irr("strive", "for a cleaner fix", "strove", "striven", { pasts: ["strived"], participles: ["strived"] }),
    irr("weep", "in the wind", "wept", "wept"),
    irr("wind", "the clock before bed", "wound", "wound"),
    irr("wring", "the wet cloth dry", "wrung", "wrung"),
    irr("learn", "the local names", "learned", "learned", { pasts: ["learnt"], participles: ["learnt"] }),
    irr("burn", "the midnight oil", "burned", "burned", { pasts: ["burnt"], participles: ["burnt"] }),
    irr("dream", "of open water", "dreamed", "dreamed", { pasts: ["dreamt"], participles: ["dreamt"] }),
    irr("prove", "the shorter route", "proved", "proved", { participles: ["proven"] }),

    regular("accept", "the invitation"),
    regular("add", "a note in the margin"),
    regular("agree", "on a later start", { stative: true }),
    regular("allow", "more time for the crossing"),
    regular("answer", "the harbor signal"),
    regular("appear", "on the eastern ridge"),
    regular("ask", "a careful question"),
    regular("believe", "the older chart", { stative: true }),
    regular("call", "the crew together"),
    regular("carry", "the spare sail"),
    regular("change", "the planned heading"),
    regular("check", "the sounding again"),
    regular("close", "the log for the night"),
    regular("consider", "a different approach"),
    regular("continue", "along the marked route"),
    regular("count", "the remaining stores"),
    regular("cover", "the ink with a blotter"),
    regular("create", "a clearer sketch"),
    regular("cross", "the bar at slack water"),
    regular("decide", "against the shortcut"),
    regular("deliver", "the packet to town"),
    regular("describe", "the wreck in detail"),
    regular("develop", "a better method"),
    regular("discover", "a hidden cove"),
    regular("drop", "the anchor in the bay"),
    regular("enter", "the narrow channel"),
    regular("explain", "the delay to the crew"),
    regular("fail", "to catch the early tide"),
    regular("fill", "the lamps before dusk"),
    regular("finish", "the morning entry"),
    regular("follow", "the inner passage"),
    regular("gather", "the scattered pages"),
    regular("happen", "sooner than expected"),
    regular("help", "the new hand on deck"),
    regular("hope", "for a quieter night"),
    regular("include", "the reef on the sketch"),
    regular("join", "the afternoon watch"),
    regular("jump", "clear of the boom"),
    regular("laugh", "at the old story"),
    regular("like", "the look of the sky", { stative: true }),
    regular("listen", "for the foghorn"),
    regular("live", "above the chart room"),
    regular("look", "at the far headland"),
    regular("love", "the work at sea", { stative: true }),
    regular("mark", "the shoal in red"),
    regular("move", "the table to the window"),
    regular("need", "a second pair of hands", { stative: true }),
    regular("notice", "the change in color"),
    regular("offer", "a warmer coat"),
    regular("open", "the logbook"),
    regular("pass", "the cape before noon"),
    regular("plan", "the next sounding"),
    regular("play", "cards after supper"),
    regular("point", "to the broken pier"),
    regular("practice", "the new knots"),
    regular("prefer", "the inshore route", { stative: true }),
    regular("prepare", "the evening meal"),
    regular("promise", "a full report"),
    regular("protect", "the pages from spray"),
    regular("pull", "the dinghy closer"),
    regular("push", "the door against the wind"),
    regular("reach", "the outer mark"),
    regular("receive", "word from shore"),
    regular("remember", "the earlier warning", { stative: true }),
    regular("repair", "the torn canvas"),
    regular("repeat", "the bearing twice"),
    regular("return", "before last light"),
    regular("save", "the last of the water"),
    regular("seem", "calmer after midnight", { stative: true }),
    regular("serve", "as a fair landmark"),
    regular("share", "the watch with a friend"),
    regular("sign", "the completed log"),
    regular("smile", "at the old joke"),
    regular("start", "the engine by hand"),
    regular("stay", "inside the marked lane"),
    regular("stop", "at the first safe pool"),
    regular("study", "the unfamiliar coast"),
    regular("support", "the weaker argument"),
    regular("talk", "through the next move"),
    regular("thank", "the pilot on the quay"),
    regular("travel", "with the morning flood"),
    regular("try", "a different approach"),
    regular("turn", "toward the inner harbor"),
    regular("use", "the older sextant"),
    regular("visit", "the chart seller"),
    regular("wait", "for the slack"),
    regular("walk", "the length of the pier"),
    regular("want", "a clearer sky", { stative: true }),
    regular("watch", "the weather to the west"),
    regular("wish", "for an earlier start"),
    regular("work", "through the long list"),
    regular("worry", "about the thin ice"),
    regular("tie", "the spare line"),
    regular("echo", "across the inlet"),
    regular("fix", "the loose hinge"),
    regular("guess", "the remaining distance"),
    regular("hurry", "toward the landing"),
    regular("copy", "the older sounding"),
    regular("reply", "with a single word"),
  ];

  const seen = new Set();
  const unique = [];
  VERBS.forEach(function (verb) {
    if (seen.has(verb.lemma)) return;
    seen.add(verb.lemma);
    unique.push(verb);
  });

  unique.sort(function (a, b) {
    return a.lemma.localeCompare(b.lemma);
  });

  return {
    VERBS: unique,
  };
});
